spring:
  application:
    name: clinident
  datasource:
    url: jdbc:mysql://localhost:3306/clinidentDB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 8888
